/**
 * Predefined UI Templates for common annotation tasks
 */

import { UITemplate, Widget } from '../../types/uiBuilder';

function makeId(): string {
  return `w-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

function makeOption(label: string, value?: string) {
  return { id: makeId(), label, value: value || label.toLowerCase().replace(/\s+/g, '_') };
}

// ─── Image Classification ─────────────────────────────────────────────────────
const imageClassificationWidgets: Widget[] = [
  {
    id: 'img-viewer',
    type: 'FILE_VIEWER',
    label: 'Image',
    required: false,
    disabled: false,
    hidden: false,
    order: 0,
    position: { x: 0, y: 0 },
    size: { width: 600, height: 400 },
    fileType: 'IMAGE',
    allowFullscreen: true,
    showControls: true,
  } as any,
  {
    id: 'img-instruction',
    type: 'INSTRUCTION_TEXT',
    label: 'Instructions',
    required: false,
    disabled: false,
    hidden: false,
    order: 1,
    position: { x: 0, y: 420 },
    size: { width: 500, height: 60 },
    content: 'Please classify the image according to the categories below. Select the most appropriate category.',
    variant: 'info',
  } as any,
  {
    id: 'img-category',
    type: 'RADIO_GROUP',
    label: 'Image Category',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 2,
    position: { x: 0, y: 500 },
    size: { width: 500, height: 160 },
    options: [
      makeOption('Person / People'),
      makeOption('Animal'),
      makeOption('Object / Product'),
      makeOption('Scene / Landscape'),
      makeOption('Text / Document'),
      makeOption('Other'),
    ],
    layout: 'vertical',
  } as any,
  {
    id: 'img-quality',
    type: 'RADIO_GROUP',
    label: 'Image Quality',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 3,
    position: { x: 0, y: 680 },
    size: { width: 500, height: 100 },
    options: [
      makeOption('High'),
      makeOption('Medium'),
      makeOption('Low'),
    ],
    layout: 'horizontal',
  } as any,
  {
    id: 'img-notes',
    type: 'TEXTAREA',
    label: 'Additional Notes',
    placeholder: 'Optional: describe anything noteworthy about the image...',
    required: false,
    disabled: false,
    hidden: false,
    order: 4,
    position: { x: 0, y: 800 },
    size: { width: 500, height: 100 },
    rows: 3,
    showCharCount: true,
  } as any,
];

// ─── Audio Transcription ──────────────────────────────────────────────────────
const audioTranscriptionWidgets: Widget[] = [
  {
    id: 'audio-viewer',
    type: 'FILE_VIEWER',
    label: 'Audio File',
    required: false,
    disabled: false,
    hidden: false,
    order: 0,
    position: { x: 0, y: 0 },
    size: { width: 600, height: 160 },
    fileType: 'AUDIO',
    showControls: true,
  } as any,
  {
    id: 'audio-instruction',
    type: 'INSTRUCTION_TEXT',
    label: 'Instructions',
    required: false,
    disabled: false,
    hidden: false,
    order: 1,
    position: { x: 0, y: 180 },
    size: { width: 500, height: 60 },
    content: 'Listen to the audio carefully and transcribe the spoken content. Include all spoken words, hesitations, and fillers (e.g., "um", "uh").',
    variant: 'info',
  } as any,
  {
    id: 'audio-transcription',
    type: 'TEXTAREA',
    label: 'Transcription',
    placeholder: 'Type the exact transcription here...',
    required: true,
    disabled: false,
    hidden: false,
    order: 2,
    position: { x: 0, y: 260 },
    size: { width: 500, height: 160 },
    rows: 6,
    showCharCount: true,
  } as any,
  {
    id: 'audio-quality',
    type: 'RADIO_GROUP',
    label: 'Audio Quality',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 3,
    position: { x: 0, y: 440 },
    size: { width: 500, height: 80 },
    options: [
      makeOption('Clear'),
      makeOption('Moderate'),
      makeOption('Poor'),
      makeOption('Inaudible'),
    ],
    layout: 'horizontal',
  } as any,
  {
    id: 'audio-speakers',
    type: 'RADIO_GROUP',
    label: 'Number of Speakers',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 4,
    position: { x: 0, y: 540 },
    size: { width: 500, height: 60 },
    options: [
      makeOption('1'),
      makeOption('2'),
      makeOption('3+'),
    ],
    layout: 'horizontal',
  } as any,
  {
    id: 'audio-confidence',
    type: 'RATING',
    label: 'Transcription Confidence',
    required: false,
    disabled: false,
    hidden: false,
    order: 5,
    position: { x: 0, y: 620 },
    size: { width: 300, height: 60 },
    maxRating: 5,
    icon: 'star',
    helpText: '1 = Very uncertain, 5 = Very confident',
  } as any,
];

// ─── Text Quality Review ──────────────────────────────────────────────────────
const textQualityWidgets: Widget[] = [
  {
    id: 'text-viewer',
    type: 'FILE_VIEWER',
    label: 'Text Content',
    required: false,
    disabled: false,
    hidden: false,
    order: 0,
    position: { x: 0, y: 0 },
    size: { width: 600, height: 300 },
    fileType: 'TEXT',
    showControls: true,
  } as any,
  {
    id: 'text-instruction',
    type: 'INSTRUCTION_TEXT',
    label: 'Instructions',
    required: false,
    disabled: false,
    hidden: false,
    order: 1,
    position: { x: 0, y: 320 },
    size: { width: 500, height: 60 },
    content: 'Evaluate the quality of the text. Rate its overall quality and identify any specific issues.',
    variant: 'info',
  } as any,
  {
    id: 'text-quality-rating',
    type: 'RATING',
    label: 'Overall Quality Rating',
    required: true,
    disabled: false,
    hidden: false,
    order: 2,
    position: { x: 0, y: 400 },
    size: { width: 300, height: 60 },
    maxRating: 5,
    icon: 'star',
    helpText: '1 = Very Poor, 5 = Excellent',
  } as any,
  {
    id: 'text-fluency',
    type: 'RADIO_GROUP',
    label: 'Fluency / Readability',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 3,
    position: { x: 0, y: 480 },
    size: { width: 500, height: 80 },
    options: [
      makeOption('Fluent'),
      makeOption('Mostly Fluent'),
      makeOption('Somewhat Fluent'),
      makeOption('Not Fluent'),
    ],
    layout: 'horizontal',
  } as any,
  {
    id: 'text-issues',
    type: 'MULTI_SELECT',
    label: 'Issues Found (select all that apply)',
    placeholder: '',
    required: false,
    disabled: false,
    hidden: false,
    order: 4,
    position: { x: 0, y: 580 },
    size: { width: 500, height: 160 },
    options: [
      makeOption('Grammar errors'),
      makeOption('Spelling errors'),
      makeOption('Factual inaccuracies'),
      makeOption('Unclear meaning'),
      makeOption('Incomplete content'),
      makeOption('Off-topic'),
      makeOption('Inappropriate content'),
    ],
  } as any,
  {
    id: 'text-feedback',
    type: 'TEXTAREA',
    label: 'Detailed Feedback',
    placeholder: 'Provide specific feedback about the text quality...',
    required: false,
    disabled: false,
    hidden: false,
    order: 5,
    position: { x: 0, y: 760 },
    size: { width: 500, height: 100 },
    rows: 4,
  } as any,
];

// ─── Video Analysis ───────────────────────────────────────────────────────────
const videoAnalysisWidgets: Widget[] = [
  {
    id: 'video-viewer',
    type: 'FILE_VIEWER',
    label: 'Video',
    required: false,
    disabled: false,
    hidden: false,
    order: 0,
    position: { x: 0, y: 0 },
    size: { width: 600, height: 360 },
    fileType: 'VIDEO',
    showControls: true,
    allowFullscreen: true,
  } as any,
  {
    id: 'video-instruction',
    type: 'INSTRUCTION_TEXT',
    label: 'Instructions',
    required: false,
    disabled: false,
    hidden: false,
    order: 1,
    position: { x: 0, y: 380 },
    size: { width: 500, height: 60 },
    content: 'Watch the video carefully before answering the questions below.',
    variant: 'info',
  } as any,
  {
    id: 'video-content-type',
    type: 'RADIO_GROUP',
    label: 'Content Type',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 2,
    position: { x: 0, y: 460 },
    size: { width: 500, height: 140 },
    options: [
      makeOption('News / Documentary'),
      makeOption('Entertainment / Media'),
      makeOption('Educational'),
      makeOption('Advertisement'),
      makeOption('User Generated'),
      makeOption('Other'),
    ],
    layout: 'vertical',
  } as any,
  {
    id: 'video-quality',
    type: 'RADIO_GROUP',
    label: 'Video Quality',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 3,
    position: { x: 0, y: 620 },
    size: { width: 500, height: 60 },
    options: [
      makeOption('HD / High'),
      makeOption('SD / Medium'),
      makeOption('Low'),
    ],
    layout: 'horizontal',
  } as any,
  {
    id: 'video-description',
    type: 'TEXTAREA',
    label: 'Brief Description',
    placeholder: 'Describe what happens in the video...',
    required: true,
    disabled: false,
    hidden: false,
    order: 4,
    position: { x: 0, y: 700 },
    size: { width: 500, height: 100 },
    rows: 4,
    showCharCount: true,
  } as any,
  {
    id: 'video-sensitive',
    type: 'CHECKBOX',
    label: 'Contains Sensitive Content',
    required: false,
    disabled: false,
    hidden: false,
    order: 5,
    position: { x: 0, y: 820 },
    size: { width: 300, height: 40 },
    checkboxLabel: 'Contains Sensitive Content',
  } as any,
];

// ─── Multi-turn Conversation ──────────────────────────────────────────────────
const conversationReviewWidgets: Widget[] = [
  {
    id: 'conv-instruction',
    type: 'INSTRUCTION_TEXT',
    label: 'Instructions',
    required: false,
    disabled: false,
    hidden: false,
    order: 0,
    position: { x: 0, y: 0 },
    size: { width: 600, height: 80 },
    content: 'Review the conversation below and evaluate the quality of the AI responses. Rate each dimension and provide overall feedback.',
    variant: 'info',
  } as any,
  {
    id: 'conv-helpfulness',
    type: 'RATING',
    label: 'Helpfulness',
    required: true,
    disabled: false,
    hidden: false,
    order: 1,
    position: { x: 0, y: 100 },
    size: { width: 400, height: 60 },
    maxRating: 5,
    icon: 'star',
    helpText: '1 = Not helpful at all, 5 = Extremely helpful',
  } as any,
  {
    id: 'conv-accuracy',
    type: 'RATING',
    label: 'Accuracy / Truthfulness',
    required: true,
    disabled: false,
    hidden: false,
    order: 2,
    position: { x: 0, y: 180 },
    size: { width: 400, height: 60 },
    maxRating: 5,
    icon: 'star',
    helpText: '1 = Very inaccurate, 5 = Highly accurate',
  } as any,
  {
    id: 'conv-safety',
    type: 'RADIO_GROUP',
    label: 'Safety / Appropriate Content',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 3,
    position: { x: 0, y: 260 },
    size: { width: 500, height: 60 },
    options: [
      makeOption('Safe', 'safe'),
      makeOption('Borderline', 'borderline'),
      makeOption('Unsafe', 'unsafe'),
    ],
    layout: 'horizontal',
  } as any,
  {
    id: 'conv-issues',
    type: 'MULTI_SELECT',
    label: 'Issues Found',
    placeholder: '',
    required: false,
    disabled: false,
    hidden: false,
    order: 4,
    position: { x: 0, y: 340 },
    size: { width: 500, height: 140 },
    options: [
      makeOption('Hallucination / Fabrication'),
      makeOption('Biased or one-sided'),
      makeOption('Unhelpful refusal'),
      makeOption('Verbose / Unnecessary info'),
      makeOption('Incomplete answer'),
      makeOption('Wrong format'),
    ],
  } as any,
  {
    id: 'conv-overall',
    type: 'RADIO_GROUP',
    label: 'Overall Response Quality',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 5,
    position: { x: 0, y: 500 },
    size: { width: 500, height: 60 },
    options: [
      makeOption('Excellent'),
      makeOption('Good'),
      makeOption('Fair'),
      makeOption('Poor'),
    ],
    layout: 'horizontal',
  } as any,
  {
    id: 'conv-feedback',
    type: 'TEXTAREA',
    label: 'Additional Comments',
    placeholder: 'Provide any specific feedback or explanations...',
    required: false,
    disabled: false,
    hidden: false,
    order: 6,
    position: { x: 0, y: 580 },
    size: { width: 500, height: 100 },
    rows: 4,
  } as any,
];

// ─── Sentiment & Tone Analysis ────────────────────────────────────────────────
const sentimentAnalysisWidgets: Widget[] = [
  {
    id: 'sent-viewer',
    type: 'FILE_VIEWER',
    label: 'Text to Analyze',
    required: false,
    disabled: false,
    hidden: false,
    order: 0,
    position: { x: 0, y: 0 },
    size: { width: 600, height: 220 },
    fileType: 'TEXT',
    showControls: false,
  } as any,
  {
    id: 'sent-instruction',
    type: 'INSTRUCTION_TEXT',
    label: 'Instructions',
    required: false,
    disabled: false,
    hidden: false,
    order: 1,
    position: { x: 0, y: 240 },
    size: { width: 500, height: 60 },
    content: 'Analyze the sentiment and tone of the text above.',
    variant: 'info',
  } as any,
  {
    id: 'sent-sentiment',
    type: 'RADIO_GROUP',
    label: 'Overall Sentiment',
    placeholder: '',
    required: true,
    disabled: false,
    hidden: false,
    order: 2,
    position: { x: 0, y: 320 },
    size: { width: 500, height: 60 },
    options: [
      makeOption('Very Positive'),
      makeOption('Positive'),
      makeOption('Neutral'),
      makeOption('Negative'),
      makeOption('Very Negative'),
    ],
    layout: 'horizontal',
  } as any,
  {
    id: 'sent-emotions',
    type: 'MULTI_SELECT',
    label: 'Emotions Detected',
    placeholder: '',
    required: false,
    disabled: false,
    hidden: false,
    order: 3,
    position: { x: 0, y: 400 },
    size: { width: 500, height: 120 },
    options: [
      makeOption('Joy'),
      makeOption('Sadness'),
      makeOption('Anger'),
      makeOption('Fear'),
      makeOption('Surprise'),
      makeOption('Disgust'),
      makeOption('None'),
    ],
  } as any,
  {
    id: 'sent-confidence',
    type: 'SLIDER',
    label: 'Confidence Score',
    required: true,
    disabled: false,
    hidden: false,
    order: 4,
    position: { x: 0, y: 540 },
    size: { width: 400, height: 60 },
    min: 0,
    max: 100,
    step: 5,
    showValue: true,
    helpText: 'How confident are you in your assessment?',
  } as any,
];

// ─── Export Templates ─────────────────────────────────────────────────────────
export const uiTemplates: UITemplate[] = [
  {
    id: 'image-classification',
    name: 'Image Classification',
    description: 'Classify images by category and quality with optional notes.',
    category: 'image',
    configuration: {
      name: 'Image Classification',
      version: 1,
      pipelineMode: 'ANNOTATION',
      fileType: 'IMAGE',
      layout: { type: 'two-column', columns: 2, gap: 16 },
      widgets: imageClassificationWidgets,
    },
  },
  {
    id: 'audio-transcription',
    name: 'Audio Transcription',
    description: 'Transcribe audio with quality and speaker annotations.',
    category: 'audio',
    configuration: {
      name: 'Audio Transcription',
      version: 1,
      pipelineMode: 'ANNOTATION',
      fileType: 'AUDIO',
      layout: { type: 'two-column', columns: 2, gap: 16 },
      widgets: audioTranscriptionWidgets,
    },
  },
  {
    id: 'text-quality-review',
    name: 'Text Quality Review',
    description: 'Evaluate text quality, fluency and identify specific issues.',
    category: 'text',
    configuration: {
      name: 'Text Quality Review',
      version: 1,
      pipelineMode: 'ANNOTATION',
      fileType: 'TEXT',
      layout: { type: 'two-column', columns: 2, gap: 16 },
      widgets: textQualityWidgets,
    },
  },
  {
    id: 'video-analysis',
    name: 'Video Analysis',
    description: 'Analyze video content type, quality and generate descriptions.',
    category: 'video',
    configuration: {
      name: 'Video Analysis',
      version: 1,
      pipelineMode: 'ANNOTATION',
      fileType: 'VIDEO',
      layout: { type: 'two-column', columns: 2, gap: 16 },
      widgets: videoAnalysisWidgets,
    },
  },
  {
    id: 'conversation-review',
    name: 'Conversation Review',
    description: 'Rate AI conversation quality across multiple dimensions.',
    category: 'multi-modal',
    configuration: {
      name: 'Conversation Quality Review',
      version: 1,
      pipelineMode: 'REVIEW',
      fileType: 'TEXT',
      layout: { type: 'single-column', columns: 1, gap: 16 },
      widgets: conversationReviewWidgets,
    },
  },
  {
    id: 'sentiment-analysis',
    name: 'Sentiment & Tone Analysis',
    description: 'Label sentiment, emotions, and confidence for text content.',
    category: 'text',
    configuration: {
      name: 'Sentiment Analysis',
      version: 1,
      pipelineMode: 'ANNOTATION',
      fileType: 'TEXT',
      layout: { type: 'two-column', columns: 2, gap: 16 },
      widgets: sentimentAnalysisWidgets,
    },
  },
];
